### PR TITLE
retina favicon

### PR DESCRIPTION
**Pull request by jamiescript**

### CODE REVIEW

**Comment by jamiescript** [comment]
@rgarcia hi, just checking if you wanted this or if not I will close this PR, thanks :surfer:

**Comment by kevinburke** [comment]
This project isn't maintained anymore. I've thought about starting a fork but haven't had any time to do so.

**Comment by rgarcia** [comment]
Yeah, sorry guys. @vecter and I are pretty busy these days. Very open to collaborating with someone who wants to take over w/ a solid fork.

**Comment by jamiescript** [comment]
No worries guys, thanks for getting back to me on this. I can totally empathise with being too busy so unfortunately I am in the same boat in that respect. In any case the retina icon is there and I will leave this PR open in case this repo is taken on by someone with a more forgiving schedule.

**Pull request closed without merging**
