### PR TITLE
Progress bar

### PR DESCRIPTION
**Pull request by yonran**
Adds a progress bar in addition to the spinner when loading the 2–10MB json files. For those browsers that support XMLHttpRequest 2.0 progress events and the `progress` element. Here’s how it looks:

screenshot

### CODE REVIEW

**Comment by rgarcia** [comment]
really cool! thanks for contributing.

**Comment by rgarcia** [comment]
so I just noticed when clicking on multiple links in succession this kind of looks weird:

screenshot

you can play around with it here: http://instacss-staging.herokuapp.com

**Comment by yonran** [comment]
hmm You're right, it's weird to see multiple spinners and bars. I'll have to try it out some more to see what's going on (e.g. when one of them finishes, do the results get drawn while the second one is still spinning?).

**Comment by rgarcia** [comment]
I'm leaning towards rolling this change back, since I'd like to push out the other updates...

**Comment by yonran** [comment]
Sure thing; it was relatively minor change. Don't keep us waiting on what you're working on!

**Pull request merged**
