### PR TITLE
Fix for vertical scroll

### PR DESCRIPTION
**Pull request by liyanchang**
Problem: Double scrollbar on right in http://db.tt/hhJWylfO

Fix: Simple css changes to remove some padding.

### CODE REVIEW

**Comment by rgarcia** [comment]
do you have a screenshot of the result?

**Comment by liyanchang** [comment]
http://db.tt/TlFkZBZM
http://db.tt/Vu78jpkJ

At both responsive and non responsive sizes.

**Comment by rgarcia** [comment]
thanks!

**Comment by liyanchang** [comment]
Glad to contribute.

**Pull request merged**
